Header header

float64 x_curr
float64 y_curr
float64 z_curr

float64 x_dot_curr
float64 y_dot_curr
float64 z_dot_curr

float64 x_ddot_curr
float64 y_ddot_curr
float64 z_ddot_curr

float64 x_des
float64 y_des
float64 z_des

float64 x_dot_des
float64 y_dot_des
float64 z_dot_des

float64 x_ddot_des
float64 y_ddot_des
float64 z_ddot_des

float64 x_err
float64 y_err
float64 z_err

float64 x_dot_err
float64 y_dot_err
float64 z_dot_err

float64 x_ddot_err
float64 y_ddot_err
float64 z_ddot_err

float64 roll_curr
float64 pitch_curr
float64 yaw_curr

float64 roll_dot_curr
float64 pitch_dot_curr
float64 yaw_dot_curr


float64 roll_des
float64 pitch_des
float64 yaw_des

float64 roll_dot_des
float64 pitch_dot_des
float64 yaw_dot_des

float64 roll_err
float64 pitch_err
float64 yaw_err

float64 roll_dot_err
float64 pitch_dot_err
float64 yaw_dot_err


float64 tau_x
float64 tau_y
float64 tau_z

float64 body_moment_x
float64 body_moment_y
float64 body_moment_z

float64 mass
float64 thrust
float64 collective_thrust

float64 quat_des0
float64 quat_des1
float64 quat_des2
float64 quat_des3


float64 pred_err_x 
float64 pred_err_y
float64 pred_err_z 